# Setup

In [1]:
import io
import requests
import rasterio
import numpy as np
import pandas as pd
import geopandas as gpd
from shapely.wkt import loads

import sys
if sys.version_info < (3, 9):
    from importlib_resources import files
else:
    from importlib.resources import files

from beak.experimental.io import check_path
from beak.experimental.conversions import create_binary_raster

In [2]:
# Set base paths and files
BASE_PATH = files("beak.data")

EPSG_CODE = 102008
RESOLUTION = 500
BASE_SPATIAL = str(EPSG_CODE) + "_" + str(RESOLUTION)
BASE_EXTENT = "laculi_southwest"

BASE_RASTER = BASE_PATH / "BASE_RASTERS" / str("EPSG_" + str(EPSG_CODE) + "_RES_" + str(RESOLUTION) + "_" + BASE_EXTENT + ".tif")
base_raster = rasterio.open(BASE_RASTER)

# Points file and query to select relevant mineral occurences
PATH_LABELS = BASE_PATH / "RAW" / "mineral_deposits" / "Lacustrine_Lithium" / "TA2_Pre_Hack_12M" / "set_20240725"
check_path(PATH_LABELS)

# Set the output file
PATH_ROOT = BASE_PATH / "PROCESSED" / str("regional" + "_" + BASE_EXTENT + "_" + BASE_SPATIAL)
PATH_EXPORT = PATH_ROOT / "labels" / str("TA2_240725_FILTERED" + ".tif")
OUT_FILE = PATH_EXPORT

print(f"Output raster: {OUT_FILE}")

Output raster: S:\Projekte\20230082_DARPA_CriticalMAAS_TA3\Bearbeitung\GitHub\beak-ta3\src\beak\data\PROCESSED\regional_102008_500_laculi_southwest\labels\TA2_240725_FILTERED.tif

In [3]:
token = ""

# Pull data from CDR

In [4]:
url_1 = 'https://api.cdr.land/v1/minerals/dedup-site/search/Lithium?with_location=true&with_deposit_types_only=true&system=minmod&top_n=1&limit=-1'
url_2 = 'https://api.cdr.land/v1/minerals/dedup-site/search/?with_location=true&with_deposit_types_only=true&system=minmod&top_n=1&limit=-1'

url = url_1

headers = {
    'accept': 'application/json',
    'Authorization': f'Bearer {token}'
}

response = requests.get(url, headers=headers)
data = response.text

In [5]:
file = io.StringIO(data)
df = pd.read_csv(file)
df

,id,record_ids,mineral_site_ids,names,type,rank,country,province,crs,centroid,...,contained_metal_unit,tonnage,tonnage_unit,grade,grade_unit,top1_deposit_type,top1_deposit_group,top1_deposit_environment,top1_deposit_classification_confidence,top1_deposit_classification_source
0,002ea762abc147288cd08c09a579c923,886a98dbf435439487b4ab7fd80306db,https://minmod.isi.edu/resource/site__mrdata-u...,Line Boy Mine,Past Producer,B,United States,Arizona,EPSG:4326,POINT (-110.6915 31.33542),...,million tonnes,NaN,million tonnes,NaN,percent,Breccia pipe copper,Breccia pipe,Magmatic hydrothermal,0.109823,"algorithm predictions, SRI deposit type classi..."
1,006f4d1a10ea4cf5ac17e86799782788,a976c33d322547bfb008a62e8cb717c2,https://minmod.isi.edu/resource/site__mrdata-u...,Anderson Mica Mines and Swanson Lithia Mine,Past Producer,B,United States,Connecticut,EPSG:4326,POINT (-72.52152 41.51499),...,million tonnes,NaN,million tonnes,NaN,percent,Simple pegmatite,Pegmatite,Magmatic,1.000000,"algorithm predictions, SRI crosswalk agent v0"
2,00f704d0e0484723bf0a1575b3251128,093f6bd12cb24c7996d9476655a109c4,https://minmod.isi.edu/resource/site__mrdata-u...,Carbonate Belle Claim,Occurrence,D,United States,Wyoming,EPSG:4326,POINT (-104.69134 41.30624),...,million tonnes,NaN,million tonnes,NaN,percent,Carbonatite niobium,Carbonatite,Magmatic,0.101381,"algorithm predictions, SRI deposit type classi..."
3,014ee2593aef46c9b3c68d35de28eab3,a86e483dcff744958707a0df18a34ec3,https://minmod.isi.edu/resource/site__mrdata-u...,Vanderburg - Katerina Pegmatite,Producer,D,United States,California,EPSG:4326,POINT (-117.08419 33.36672),...,million tonnes,NaN,million tonnes,NaN,percent,Simple pegmatite,Pegmatite,Magmatic,1.000000,"algorithm predictions, SRI crosswalk agent v0"
4,019dfd77586f47fa821d7fa9261e1959,fd874542c49344349b3ccdc0f5aa430b,https://minmod.isi.edu/resource/site__mrdata-u...,Unknown Name,Occurrence,D,Ecuador,Pichincha,EPSG:4326,POINT (-78.34978 -0.11507),...,million tonnes,NaN,million tonnes,NaN,percent,Lacustrine clay lithium,Clay,Basin evaporative,0.406181,"algorithm predictions, SRI deposit type classi..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
452,fbb30fb681554201963deb19ea4c77b6,57943546ae014d26bc9611819ee38745,https://minmod.isi.edu/resource/site__mrdata-u...,Perry Prospect,Prospect,D,United States,Maine,EPSG:4326,POINT (-70.46082 44.52136),...,million tonnes,NaN,million tonnes,NaN,percent,LCT pegmatite,Pegmatite,Magmatic,0.305974,"algorithm predictions, SRI deposit type classi..."
453,fc6b7849d50242c8a721a711136c59e3,2ca981f598b048feae1355687b6ed061,https://minmod.isi.edu/resource/site__mrdata-u...,Mdara-Nigel Complex,Producer,D,Zimbabwe,NaN,EPSG:4326,POINT (31.43464 -19.9302),...,million tonnes,NaN,million tonnes,NaN,percent,Greisen beryllium±Li,Greisen,Magmatic hydrothermal,0.635058,"algorithm predictions, SRI deposit type classi..."
454,fc7ea10595744ddb96ed61c4849c07f4,7981f648d5d8449a8d71333fc2691ed1,https://minmod.isi.edu/resource/site__mrdata-u...,Stalin,Past Producer,D,United States,South Dakota,EPSG:4326,POINT (-103.62637 43.85496),...,million tonnes,NaN,million tonnes,NaN,percent,Peralkaline igneous HFSE- REE,Peralkaline igneous,Magmatic,0.378105,"algorithm predictions, SRI deposit type classi..."
455,fcff002c50ac4226971afcf238689e39,fd46fa8a38e84000b24e2b1922d0d8d3,https://minmod.isi.edu/resource/site__mrdata-u...,Dunton Mine,Past Producer,D,United States,Maine,EPSG:4326,POINT (-70.72363 44.54276),...,million tonnes,NaN,million tonnes,NaN,percent,Simple pegmatite,Pegmatite,Magmatic,0.388430,"algorithm predictions, SRI deposit type classi..."
456,fe330866dc2246bd87b91f2030761f97,6508ed22652c44789b1e30b2fc343b7e,https://minmod.isi.edu/resource/site__mrdata-u...,Laguna Blanca Yacimiento,Occurrence,D,Peru,Tacna,EPSG:4326,POINT (-70.13956 -17.57767),...,million tonnes,NaN,million tonnes,NaN,percent,Lacustrine brine lithium,Brine,Basin evaporative,0.794244,"algorithm predictions, SRI deposit type classi..."

## Create geodataframe and clear data

In [6]:
mineral_sites = df.copy()
mineral_sites["geometry"] = mineral_sites["wkt"].apply(loads)
mineral_sites = gpd.GeoDataFrame(mineral_sites, crs="EPSG:4326")
mineral_sites = mineral_sites.explode(column="geometry", ignore_index=True)
mineral_sites = mineral_sites.drop_duplicates(subset=["geometry"])
mineral_sites

,id,record_ids,mineral_site_ids,names,type,rank,country,province,crs,centroid,...,tonnage,tonnage_unit,grade,grade_unit,top1_deposit_type,top1_deposit_group,top1_deposit_environment,top1_deposit_classification_confidence,top1_deposit_classification_source,geometry
0,002ea762abc147288cd08c09a579c923,886a98dbf435439487b4ab7fd80306db,https://minmod.isi.edu/resource/site__mrdata-u...,Line Boy Mine,Past Producer,B,United States,Arizona,EPSG:4326,POINT (-110.6915 31.33542),...,NaN,million tonnes,NaN,percent,Breccia pipe copper,Breccia pipe,Magmatic hydrothermal,0.109823,"algorithm predictions, SRI deposit type classi...",POINT (-110.69150 31.33542)
1,006f4d1a10ea4cf5ac17e86799782788,a976c33d322547bfb008a62e8cb717c2,https://minmod.isi.edu/resource/site__mrdata-u...,Anderson Mica Mines and Swanson Lithia Mine,Past Producer,B,United States,Connecticut,EPSG:4326,POINT (-72.52152 41.51499),...,NaN,million tonnes,NaN,percent,Simple pegmatite,Pegmatite,Magmatic,1.000000,"algorithm predictions, SRI crosswalk agent v0",POINT (-72.52152 41.51499)
2,00f704d0e0484723bf0a1575b3251128,093f6bd12cb24c7996d9476655a109c4,https://minmod.isi.edu/resource/site__mrdata-u...,Carbonate Belle Claim,Occurrence,D,United States,Wyoming,EPSG:4326,POINT (-104.69134 41.30624),...,NaN,million tonnes,NaN,percent,Carbonatite niobium,Carbonatite,Magmatic,0.101381,"algorithm predictions, SRI deposit type classi...",POINT (-104.69134 41.30624)
3,014ee2593aef46c9b3c68d35de28eab3,a86e483dcff744958707a0df18a34ec3,https://minmod.isi.edu/resource/site__mrdata-u...,Vanderburg - Katerina Pegmatite,Producer,D,United States,California,EPSG:4326,POINT (-117.08419 33.36672),...,NaN,million tonnes,NaN,percent,Simple pegmatite,Pegmatite,Magmatic,1.000000,"algorithm predictions, SRI crosswalk agent v0",POINT (-117.08419 33.36672)
4,019dfd77586f47fa821d7fa9261e1959,fd874542c49344349b3ccdc0f5aa430b,https://minmod.isi.edu/resource/site__mrdata-u...,Unknown Name,Occurrence,D,Ecuador,Pichincha,EPSG:4326,POINT (-78.34978 -0.11507),...,NaN,million tonnes,NaN,percent,Lacustrine clay lithium,Clay,Basin evaporative,0.406181,"algorithm predictions, SRI deposit type classi...",POINT (-78.34978 -0.11507)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
635,fbb30fb681554201963deb19ea4c77b6,57943546ae014d26bc9611819ee38745,https://minmod.isi.edu/resource/site__mrdata-u...,Perry Prospect,Prospect,D,United States,Maine,EPSG:4326,POINT (-70.46082 44.52136),...,NaN,million tonnes,NaN,percent,LCT pegmatite,Pegmatite,Magmatic,0.305974,"algorithm predictions, SRI deposit type classi...",POINT (-70.46082 44.52136)
636,fc6b7849d50242c8a721a711136c59e3,2ca981f598b048feae1355687b6ed061,https://minmod.isi.edu/resource/site__mrdata-u...,Mdara-Nigel Complex,Producer,D,Zimbabwe,NaN,EPSG:4326,POINT (31.43464 -19.9302),...,NaN,million tonnes,NaN,percent,Greisen beryllium±Li,Greisen,Magmatic hydrothermal,0.635058,"algorithm predictions, SRI deposit type classi...",POINT (31.43464 -19.93020)
637,fc7ea10595744ddb96ed61c4849c07f4,7981f648d5d8449a8d71333fc2691ed1,https://minmod.isi.edu/resource/site__mrdata-u...,Stalin,Past Producer,D,United States,South Dakota,EPSG:4326,POINT (-103.62637 43.85496),...,NaN,million tonnes,NaN,percent,Peralkaline igneous HFSE- REE,Peralkaline igneous,Magmatic,0.378105,"algorithm predictions, SRI deposit type classi...",POINT (-103.62637 43.85496)
638,fcff002c50ac4226971afcf238689e39,fd46fa8a38e84000b24e2b1922d0d8d3,https://minmod.isi.edu/resource/site__mrdata-u...,Dunton Mine,Past Producer,D,United States,Maine,EPSG:4326,POINT (-70.72363 44.54276),...,NaN,million tonnes,NaN,percent,Simple pegmatite,Pegmatite,Magmatic,0.388430,"algorithm predictions, SRI deposit type classi...",POINT (-70.72363 44.54276)
639,fe330866dc2246bd87b91f2030761f97,6508ed22652c44789b1e30b2fc343b7e,https://minmod.isi.edu/resource/site__mrdata-u...,Laguna Blanca Yacimiento,Occurrence,D,Peru,Tacna,EPSG:4326,POINT (-70.13956 -17.57767),...,NaN,million tonnes,NaN,percent,Lacustrine brine lithium,Brine,Basin evaporative,0.794244,"algorithm predictions, SRI deposit type classi...",POINT (-70.13956 -17.57767)

Export

In [7]:
out_file_csv = PATH_LABELS / "mineral_sites_01_no_filter.csv"
out_file_gpkg = PATH_LABELS / "mineral_sites.gpkg"

mineral_sites.to_csv(out_file_csv, index=False)
mineral_sites.to_file(out_file_gpkg, driver="GPKG", layer="mineral_sites_01_no_filter_wkt")

# Filtering

## Basic filter

In [8]:
QUERY = "top1_deposit_classification_confidence >= 0.5 and type in ('Past Producer', 'Prospect', 'Producer') and rank in ('A', 'B', 'C') and country == 'United States'"

mineral_sites_filtered = mineral_sites.copy()
mineral_sites_filtered = mineral_sites_filtered.query(QUERY)
mineral_sites_filtered

,id,record_ids,mineral_site_ids,names,type,rank,country,province,crs,centroid,...,tonnage,tonnage_unit,grade,grade_unit,top1_deposit_type,top1_deposit_group,top1_deposit_environment,top1_deposit_classification_confidence,top1_deposit_classification_source,geometry
1,006f4d1a10ea4cf5ac17e86799782788,a976c33d322547bfb008a62e8cb717c2,https://minmod.isi.edu/resource/site__mrdata-u...,Anderson Mica Mines and Swanson Lithia Mine,Past Producer,B,United States,Connecticut,EPSG:4326,POINT (-72.52152 41.51499),...,NaN,million tonnes,NaN,percent,Simple pegmatite,Pegmatite,Magmatic,1.000000,"algorithm predictions, SRI crosswalk agent v0",POINT (-72.52152 41.51499)
7,02a6180f9b194903be554272862cc52c,"['01286193642b4b3b994f08697c9f2c23', '2ba57112...",['https://minmod.isi.edu/resource/site__mrdata...,['NI 43-101 Technical Report for the Kings Val...,Prospect,B,United States,Nevada,EPSG:4326,POINT (-118.0719325 41.722665),...,0.00009,million tonnes,0.27,percent,Lacustrine clay lithium,Clay,Basin evaporative,0.964834,"algorithm predictions, SRI deposit type classi...",POINT (-118.10909 41.76208)
8,02a6180f9b194903be554272862cc52c,"['01286193642b4b3b994f08697c9f2c23', '2ba57112...",['https://minmod.isi.edu/resource/site__mrdata...,['NI 43-101 Technical Report for the Kings Val...,Prospect,B,United States,Nevada,EPSG:4326,POINT (-118.0719325 41.722665),...,0.00009,million tonnes,0.27,percent,Lacustrine clay lithium,Clay,Basin evaporative,0.964834,"algorithm predictions, SRI deposit type classi...",POINT (-118.03477 41.68325)
25,081ba0867c3d4f88bad288f2d7830c8e,b7698b6a968a431189f9b876144e899f,https://minmod.isi.edu/resource/site__mrdata-u...,Mateen,Past Producer,B,United States,South Dakota,EPSG:4326,POINT (-103.57666 43.92306),...,NaN,million tonnes,NaN,percent,LCT pegmatite,Pegmatite,Magmatic,0.898854,"algorithm predictions, SRI deposit type classi...",POINT (-103.57666 43.92306)
44,0f9046fb2a5c4627a8518feb34d89c08,0be1bd61e8014623b12688b4adf9bb04,https://minmod.isi.edu/resource/site__mrdata-u...,White Basin,Past Producer,B,United States,Nevada,EPSG:4326,POINT (-114.57499 36.3311),...,NaN,million tonnes,NaN,percent,Lacustrine evaporite borate,Evaporite,Basin evaporative,1.000000,"algorithm predictions, SRI crosswalk agent v0",POINT (-114.57499 36.33110)
48,11a3113ef7004050955c85e7b84a813a,6ed547e6bc434a54890c59ec5068de38,https://minmod.isi.edu/resource/site__mrdata-u...,Rattlesnake Park Mine,Producer,B,United States,Colorado,EPSG:4326,POINT (-105.29837 40.35637),...,NaN,million tonnes,NaN,percent,Simple pegmatite,Pegmatite,Magmatic,0.576129,"algorithm predictions, SRI deposit type classi...",POINT (-105.29837 40.35637)
66,1a3bf6ebd7014c06a86b9c04f0d0c26f,3faba0ed896e4c9c9a146e4496198d74,https://minmod.isi.edu/resource/site__mrdata-u...,Kings Mountain Mine,Past Producer,C,United States,North Carolina,EPSG:4326,POINT (-81.34402 35.24821),...,NaN,million tonnes,NaN,percent,Greisen tin ±W-Mo,Greisen,Magmatic- Magmatic hydrothermal,0.555381,"algorithm predictions, SRI deposit type classi...",POINT (-81.34402 35.24821)
71,1cc0596a26174e3eac92142573c2c41d,3278fb7ba51748d8aee764d73c25a5d2,https://minmod.isi.edu/resource/site__mrdata-u...,Phelps Lode,Past Producer,B,United States,South Dakota,EPSG:4326,POINT (-103.61389 43.80802),...,NaN,million tonnes,NaN,percent,Simple pegmatite,Pegmatite,Magmatic,0.596119,"algorithm predictions, SRI deposit type classi...",POINT (-103.61389 43.80802)
81,1ffb757a71904c1db58ab5373356fd45,46a946b3e989473bb56c8147fccf244c,https://minmod.isi.edu/resource/site__mrdata-u...,Mount Wheeler,Past Producer,B,United States,Nevada,EPSG:4326,POINT (-114.34001 38.90106),...,NaN,million tonnes,NaN,percent,Vein tungsten,Vein,Magmatic hydrothermal,1.000000,"algorithm predictions, SRI crosswalk agent v0",POINT (-114.34001 38.90106)
106,26f241675e7d44f2a42ada89b6096707,60c51d8331674b46b00db17be93c80ba,https://minmod.isi.edu/resource/site__mrdata-u...,Century Lode Claim,Past Producer,B,United States,South Dakota,EPSG:4326,POINT (-103.57445 43.91996),...,NaN,million tonnes,NaN,percent,LCT pegmatite,Pegmatite,Magmatic,0.781714,"algorithm predictions, SRI deposit type classi...",POINT (-103.57445 43.91996)
136,30b9f37025a1404f8ec3d5db4fc42949,729d0ff8462f451a83883f02a4e369e9,https://minmod.isi.edu/resource/site__mrdata-u...,Indian Creek Deposit,Producer,C,United States,North Carolina,EPSG:4326,POINT (-81.25315 35.42371),...,NaN,million tonnes,NaN,percent,LCT pegmatite,Pegmatite,Magmatic,0.777667,"algorithm predictions, SRI deposit type classi...",POINT (-81.25315 35.42371)
144,33b8f39f7ef64458aecbe280ba8b520c,cfbe1aad100643798247d5df38f3e9d0,https://minmod.isi.edu/resource/site__mrdata-u...,Rainbow #2 Prospect,Past Producer,B,United States,Utah,EPSG:4326,POINT (-113.20832 39.70688),...,NaN,million tonnes,NaN,percent,Epithermal beryllium,Epithermal,Magmatic hydrothermal,0.704387,"algorithm predictions, SRI deposit type classi...",POINT (-113.20832 39.70688)
182,42a1590c93c540feb44312f9ddc09841,"['1d1419b6126142eda2384b51fa906c03', 'f1c44d51...",https://minmod.isi.edu/resource/site__mrdata-u...,"['Giant-Volney Pegmatite', 'Tantalum Hill Pegm...",Past Producer,C,United States,South Dakota,EPSG:4326,POINT (-104.05668 44.37636),...,NaN,million tonnes,NaN,percent,LCT pegmatite,Pegmatite,Magmatic,0.720022,"algorithm predictions, SRI deposit type classi...",POINT (-104.05668 44.37636)
188,45860632e6994153bc9cce01cd089980,"['9763d4982e4844f6a84d0b3b8e9801b1', '898548c5...",['https://minmod.isi.edu/resource/site__mrdata...,"['Tip Top Lode', 'Tiptop Lode']",Past Producer,B,United States,South Dakota,EPSG:4326,POINT (-103.66974 43.71552),...,NaN,million tonnes,NaN,percent,Simple pegmatite,Pegmatite,Magmatic,0.815704,"algorithm predictions, SRI deposit type classi...",POINT (-103.66974 43.71552)
197,4b04f7aad3914bda8f750e58c4e9b476,c228de7de84a409c8795dd2212132cea,https://minmod.isi.edu/resource/site__mrdata-u...,Foote Lithium Brine Operation.,Producer,B,United States,Nevada,EPSG:4326,POINT (-117.5912 37.75855),...,NaN,million tonnes,NaN,percent,Lacustrine brine lithium,Brine,Basin evaporative,0.993826,"algorithm predictions, SRI deposit type classi...",POINT (-117.59120 37.75855)
216,4f8a7ed81c9d407091f6e70f2ce3c392,0438e4ccdf1649be97cca4da074fb38a,https://minmod.isi.edu/resource/site__mrdata-u...,Beecher Lode,Past Producer,B,United States,South Dakota,EPSG:4326,POINT (-103.5775 43.70274),...,NaN,million tonnes,NaN,percent,LCT pegmatite,Pegmatite,Magmatic,0.608590,"algorithm predictions, SRI deposit type classi...",POINT (-103.57750 43.70274)
218,50c9bb89172b4ff394be05fa3c4e6171,"['4e2f34f37d734a068cc35d8442d7cb49', '6b033272...",https://minmod.isi.edu/resource/site__mrdata-u...,"['McDermitt Mine', 'Mcdermitt Mine']",Past Producer,A,United States,Nevada,EPSG:4326,POINT (-117.812 41.919),...,NaN,million tonnes,NaN,percent,Epithermal mercury,Epithermal,Magmatic hydrothermal,1.000000,"algorithm predictions, SRI crosswalk agent v0",POINT (-117.81200 41.91900)
228,5419818d0da74fba96f94b88f29cc4c5,0cc029ac236d404ab992d124e574db21,https://minmod.isi.edu/resource/site__mrdata-u...,Hector,Producer,B,United States,California,EPSG:4326,POINT (-116.45086 34.76668),...,NaN,million tonnes,NaN,percent,Lacustrine clay lithium,Clay,Basin evaporative,0.802968,"algorithm predictions, SRI deposit type classi...",POINT (-116.45086 34.76668)
235,5691d6ad32a34f6c91444487560e061a,56ac228df98547e09a2509bc8d066fdc,https://minmod.isi.edu/resource/site__mrdata-u...,Jones Tin Mine,Past Producer,B,United States,North Carolina,EPSG:4326,POINT (-81.31565 35.32788),...,NaN,million tonnes,NaN,percent,Greisen tin ±W-Mo,Greisen,Magmatic- Magmatic hydrothermal,0.651427,"algorithm predictions, SRI deposit type classi...",POINT (-81.31565 35.32788)
263,63356d3e84c9454abf86db9dd2378b76,"['a10b31a2c8284da18b5c3550f43b1072', '6db2edd8...",['https://minmod.isi.edu/resource/site__mrdata...,"['Blue Chalk Mine', 'Blue Chalk']",Past Producer,B,United States,Utah,EPSG:4326,POINT (-113.2211 39.70744),...,NaN,million tonnes,NaN,percent,Epithermal beryllium,Epithermal,Magmatic hydrothermal,0.986725,"algorithm predictions, SRI deposit type classi...",POINT (-113.22110 39.70744)
307,76230a5aa9764ab29aa460b2b61b2322,d446a37b63544c32bf56aaf03ad542f5,https://minmod.isi.edu/resource/site__mrdata-u...,Da,Prospect,C,United States,South Dakota,EPSG:4326,POINT (-103.52196 43.93026),...,NaN,million tonnes,NaN,percent,LCT pegmatite,Pegmatite,Magmatic,0.640041,"algorithm predictions, SRI deposit type classi...",POINT (-103.52196 43.93026)
310,77d85d4d5fc0405e9421fc6cc63081c4,cbf6bf2d62d841aeafd1fa60f472d84f,https://minmod.isi.edu/resource/site__mrdata-u...,Dunton Gem Mine,Past Producer,C,United States,Maine,EPSG:4326,POINT (-70.72329 44.5406),...,NaN,million tonnes,NaN,percent,LCT pegmatite,Pegmatite,Magmatic,0.765875,"algorithm predictions, SRI deposit type classi...",POINT (-70.72329 44.54060)
311,78c6a595cdad430bbda76a949a374a9b,1c9417172e704fed9fd8b6139009a37f,https://minmod.isi.edu/resource/site__mrdata-u...,Old Well Tin Mine Shaft,Past Producer,B,United States,North Carolina,EPSG:4326,POINT (-81.2426 35.42538),...,NaN,million tonnes,NaN,percent,Greisen tin ±W-Mo,Greisen,Magmatic- Magmatic hydrothermal,0.625062,"algorithm predictions, SRI deposit type classi...",POINT (-81.24260 35.42538)
329,8629d99d3d6e482bae652a3b2c52602d,fd3f81102fca43caa377beb00d082688,https://minmod.isi.edu/resource/site__mrdata-u...,Beecher No. 2,Past Producer,C,United States,South Dakota,EPSG:4326,POINT (-103.57639 43.70718),...,NaN,million tonnes,NaN,percent,LCT pegmatite,Pegmatite,Magmatic,0.599152,"algorithm predictions, SRI deposit type classi...",POINT (-103.57639 43.70718)
336,87db44ef21d04c5ea982ab9c53935741,9572f735946f46b1adebd5e1f61ce91a,https://minmod.isi.edu/resource/site__mrdata-u...,Opalite,Past Producer,B,United States,Oregon,EPSG:4326,POINT (-118.03471 42.05222),...,NaN,million tonnes,NaN,percent,Epithermal mercury,Epithermal,Magmatic hydrothermal,1.000000,"algorithm predictions, SRI crosswalk agent v0",POINT (-118.03471 42.05222)
358,8f6b14804c8748d388dbc8b6b483f716,ed4968de38754f159c66f98beff20237,https://minmod.isi.edu/resource/site__mrdata-u...,Oreville Spar Mica Mine,Past Producer,B,United States,South Dakota,EPSG:4326,POINT (-103.62557 43.85996),...,NaN,million tonnes,NaN,percent,Simple pegmatite,Pegmatite,Magmatic,0.514522,"algorithm predictions, SRI deposit type classi...",POINT (-103.62557 43.85996)
374,95b15864b44c4188bda3042c7416583f,8a4ee9597a34439786c7cf1eff434884,https://minmod.isi.edu/resource/site__mrdata-u...,Carpenter and Hastings Tin Mine,Past Producer,B,United States,North Carolina,EPSG:4326,POINT (-81.27954 35.38399),...,NaN,million tonnes,NaN,percent,Greisen tin ±W-Mo,Greisen,Magmatic- Magmatic hydrothermal,0.786282,"algorithm predictions, SRI deposit type classi...",POINT (-81.27954 35.38399)
389,9965756a62864831a030b2d264d56972,"['ef8f0cacab2a4776960636d8a9a747b0', '6ae24534...",['https://minmod.isi.edu/resource/site__mrdata...,"['E. C. Faires Property', 'Faires Tin Mine', '...",Past Producer,B,United States,North Carolina,EPSG:4326,POINT (-81.33924 35.246895),...,NaN,million tonnes,NaN,percent,Greisen tin ±W-Mo,Greisen,Magmatic- Magmatic hydrothermal,0.644760,"algorithm predictions, SRI deposit type classi...",POINT (-81.32926 35.27288)
390,9965756a62864831a030b2d264d56972,"['ef8f0cacab2a4776960636d8a9a747b0', '6ae24534...",['https://minmod.isi.edu/resource/site__mrdata...,"['E. C. Faires Property', 'Faires Tin Mine', '...",Past Producer,B,United States,North Carolina,EPSG:4326,POINT (-81.33924 35.246895),...,NaN,million tonnes,NaN,percent,Greisen tin ±W-Mo,Greisen,Magmatic- Magmatic hydrothermal,0.644760,"algorithm predictions, SRI deposit type classi...",POINT (-81.34922 35.22091)
394,9aef715894504d67afa907644b6c4dfd,79a45a09db7e430386bccdf757283d23,https://minmod.isi.edu/resource/site__mrdata-u...,Scott's Rose Quartz Mine,Past Producer,B,United States,South Dakota,EPSG:4326,POINT (-103.51584 43.71579),...,NaN,million tonnes,NaN,percent,Simple pegmatite,Pegmatite,Magmatic,0.520487,"algorithm predictions, SRI deposit type classi...",POINT (-103.51584 43.71579)
405,9f80310103a344bebfe186e71755eda5,083778b889bf479baf74796adf0a3782,https://minmod.isi.edu/resource/site__mrdata-u...,Spor Mountain district,Producer,B,United States,Utah,EPSG:4326,POINT (-113.217 39.707),...,NaN,million tonnes,NaN,percent,Epithermal beryllium,Epithermal,Magmatic hydrothermal,0.788627,"algorithm predictions, SRI deposit type classi...",POINT (-113.21700 39.70700)
419,a369ba0897f34c36995fbfcbd00e31d3,"['ca0bf10147204282871101037e9b83cc', '532d5db4...",['https://minmod.isi.edu/resource/site__mrdata...,"['Upper Mostellar Mine Cut', 'J. Mostellar Tin...",Past Producer,B,United States,North Carolina,EPSG:4326,POINT (-81.241905 35.42385),...,NaN,million tonnes,NaN,percent,Greisen tin ±W-Mo,Greisen,Magmatic- Magmatic hydrothermal,0.639764,"algorithm predictions, SRI deposit type classi...",POINT (-81.23899 35.42510)
420,a369ba0897f34c36995fbfcbd00e31d3,"['ca0bf10147204282871101037e9b83cc', '532d5db4...",['https://minmod.isi.edu/resource/site__mrdata...,"['Upper Mostellar Mine Cut', 'J. Mostellar Tin...",Past Producer,B,United States,North Carolina,EPSG:4326,POINT (-81.241905 35.42385),...,NaN,million tonnes,NaN,percent,Greisen tin ±W-Mo,Greisen,Magmatic- Magmatic hydrothermal,0.639764,"algorithm predictions, SRI deposit type classi...",POINT (-81.24482 35.42260)
422,a53305c1acc241c1ad7a2408ff5c2f8b,"['a584b299f4dc4a3eaa969345e1876786', '31913711...",['https://minmod.isi.edu/resource/site__mrdata...,"['Sigma Emma', 'Sigma Emma Mine']",Past Producer,B,United States,Utah,EPSG:4326,POINT (-113.2211 39.71911),...,NaN,million tonnes,NaN,percent,Epithermal beryllium,Epithermal,Magmatic hydrothermal,0.986729,"algorithm predictions, SRI deposit type classi...",POINT (-113.22110 39.71911)
451,b63dc0137d234b4a9a4ef496a0ec5a65,d60c58707f664fd382379c9beca4be02,https://minmod.isi.edu/resource/site__mrdata-u...,Blue Ridge Mine and Placer,Past Producer,B,United States,North Carolina,EPSG:4326,POINT (-81.36204 35.21205),...,NaN,million tonnes,NaN,percent,Greisen tin ±W-Mo,Greisen,Magmatic- Magmatic hydrothermal,0.574468,"algorithm predictions, SRI deposit type classi...",POINT (-81.36204 35.21205)
486,c16cd4af9cfb417d9bb923b24a118564,6e7a1060b4004d9abd7f701968775d71,https://minmod.isi.edu/resource/site__mrdata-u...,Hyatt Ranch Mine,Producer,B,United States,Colorado,EPSG:4326,POINT (-105.35337 40.4597),...,NaN,million tonnes,NaN,percent,Simple pegmatite,Pegmatite,Magmatic,0.578439,"algorithm predictions, SRI deposit type classi...",POINT (-105.35337 40.45970)
510,cc4ba06d69f74e52809d8a325e4a75eb,b2e9a275619b426d955031ebb320b6ed,https://minmod.isi.edu/resource/site__mrdata-u...,Silver Peak Marsh,Producer,B,United States,Nevada,EPSG:4326,POINT (-117.63981 37.75272),...,NaN,million tonnes,NaN,percent,Lacustrine brine lithium,Brine,Basin evaporative,0.982076,"algorithm predictions, SRI deposit type classi...",POINT (-117.63981 37.75272)
512,cca5bb3ed1424b2a84b55ca8c605f81e,c8cb5b68764d4c94ad474ceca59f0107,https://minmod.isi.edu/resource/site__mrdata-u...,Morning Star Prospect,Past Producer,B,United States,Arizona,EPSG:4326,POINT (-112.5738 33.95256),...,NaN,million tonnes,NaN,percent,Simple pegmatite,Pegmatite,Magmatic,0.792168,"algorithm predictions, SRI deposit type classi...",POINT (-112.57380 33.95256)
568,e427bde68d724ff9b9d79f1cb5c83aee,2c769def932d495d838b8764f2182468,https://minmod.isi.edu/resource/site__mrdata-u...,Nevel Mine,Past Producer,C,United States,Maine,EPSG:4326,POINT (-70.72194 44.54306),...,NaN,million tonnes,NaN,percent,Simple pegmatite,Pegmatite,Magmatic,0.533374,"algorithm predictions, SRI deposit type classi...",POINT (-70.72194 44.54306)
588,e7c4ff09bd4d4c80ac86a528b20a50e4,15b5ad3c73364cd0ae03c706ab08b6d3,https://minmod.isi.edu/resource/site__mrdata-u...,Whitesides and Kizer Mines,Past Producer,B,United States,North Carolina,EPSG:4326,POINT (-81.2951 35.37316),...,NaN,million tonnes,NaN,percent,Greisen tin ±W-Mo,Greisen,Magmatic- Magmatic hydrothermal,0.732298,"algorithm predictions, SRI deposit type classi...",POINT (-81.29510 35.37316)
592,e8b6cb42101d4f72aa79be91e5426420,b4f60446358749b2a2318a09b702e1a0,https://minmod.isi.edu/resource/site__mrdata-u...,Murphy-Houser Spodumene Deposit,Producer,C,United States,North Carolina,EPSG:4326,POINT (-81.29704 35.38538),...,NaN,million tonnes,NaN,percent,LCT pegmatite,Pegmatite,Magmatic,0.734170,"algorithm predictions, SRI deposit type classi...",POINT (-81.29704 35.38538)
626,f54bf6d99f9c45a492326642c32ddbac,15994c4a6de743a180608bcf09fe1b6d,https://minmod.isi.edu/resource/site__mrdata-u...,Henry Tin Mine Shaft,Past Producer,B,United States,North Carolina,EPSG:4326,POINT (-81.24093 35.43399),...,NaN,million tonnes,NaN,percent,Greisen tin ±W-Mo,Greisen,Magmatic- Magmatic hydrothermal,0.611848,"algorithm predictions, SRI deposit type classi...",POINT (-81.24093 35.43399)

Export

In [9]:
out_file_csv = PATH_LABELS / "mineral_sites_02_basic_filter.csv"
out_file_gpkg = PATH_LABELS / "mineral_sites.gpkg"

mineral_sites_filtered.to_csv(out_file_csv, index=False)
mineral_sites_filtered.to_file(out_file_gpkg, driver="GPKG", layer="mineral_sites_02_basic_filter_wkt")

In [10]:
column = "top1_deposit_type"
deposit_types = mineral_sites_filtered[column].unique()
deposit_types = pd.DataFrame(deposit_types, columns=[column])
deposit_types

             top1_deposit_type
0             Simple pegmatite
1      Lacustrine clay lithium
2                LCT pegmatite
3  Lacustrine evaporite borate
4            Greisen tin ±W-Mo
5                Vein tungsten
6         Epithermal beryllium
7     Lacustrine brine lithium
8           Epithermal mercury

## Final filtering

In [11]:
QUERY = "top1_deposit_type in ('Lacustrine clay lithium', 'Lacustrine evaporite borate', 'Lacustrine brine lithium') and top1_deposit_classification_confidence >= 0.5 and type in ('Past Producer', 'Prospect', 'Producer') and rank in ('A', 'B', 'C') and country == 'United States'"

mineral_sites_filtered = mineral_sites.copy()
mineral_sites_filtered = mineral_sites_filtered.query(QUERY)
mineral_sites_filtered

,id,record_ids,mineral_site_ids,names,type,rank,country,province,crs,centroid,...,tonnage,tonnage_unit,grade,grade_unit,top1_deposit_type,top1_deposit_group,top1_deposit_environment,top1_deposit_classification_confidence,top1_deposit_classification_source,geometry
7,02a6180f9b194903be554272862cc52c,"['01286193642b4b3b994f08697c9f2c23', '2ba57112...",['https://minmod.isi.edu/resource/site__mrdata...,['NI 43-101 Technical Report for the Kings Val...,Prospect,B,United States,Nevada,EPSG:4326,POINT (-118.0719325 41.722665),...,0.00009,million tonnes,0.27,percent,Lacustrine clay lithium,Clay,Basin evaporative,0.964834,"algorithm predictions, SRI deposit type classi...",POINT (-118.10909 41.76208)
8,02a6180f9b194903be554272862cc52c,"['01286193642b4b3b994f08697c9f2c23', '2ba57112...",['https://minmod.isi.edu/resource/site__mrdata...,['NI 43-101 Technical Report for the Kings Val...,Prospect,B,United States,Nevada,EPSG:4326,POINT (-118.0719325 41.722665),...,0.00009,million tonnes,0.27,percent,Lacustrine clay lithium,Clay,Basin evaporative,0.964834,"algorithm predictions, SRI deposit type classi...",POINT (-118.03477 41.68325)
44,0f9046fb2a5c4627a8518feb34d89c08,0be1bd61e8014623b12688b4adf9bb04,https://minmod.isi.edu/resource/site__mrdata-u...,White Basin,Past Producer,B,United States,Nevada,EPSG:4326,POINT (-114.57499 36.3311),...,NaN,million tonnes,NaN,percent,Lacustrine evaporite borate,Evaporite,Basin evaporative,1.000000,"algorithm predictions, SRI crosswalk agent v0",POINT (-114.57499 36.33110)
197,4b04f7aad3914bda8f750e58c4e9b476,c228de7de84a409c8795dd2212132cea,https://minmod.isi.edu/resource/site__mrdata-u...,Foote Lithium Brine Operation.,Producer,B,United States,Nevada,EPSG:4326,POINT (-117.5912 37.75855),...,NaN,million tonnes,NaN,percent,Lacustrine brine lithium,Brine,Basin evaporative,0.993826,"algorithm predictions, SRI deposit type classi...",POINT (-117.59120 37.75855)
228,5419818d0da74fba96f94b88f29cc4c5,0cc029ac236d404ab992d124e574db21,https://minmod.isi.edu/resource/site__mrdata-u...,Hector,Producer,B,United States,California,EPSG:4326,POINT (-116.45086 34.76668),...,NaN,million tonnes,NaN,percent,Lacustrine clay lithium,Clay,Basin evaporative,0.802968,"algorithm predictions, SRI deposit type classi...",POINT (-116.45086 34.76668)
510,cc4ba06d69f74e52809d8a325e4a75eb,b2e9a275619b426d955031ebb320b6ed,https://minmod.isi.edu/resource/site__mrdata-u...,Silver Peak Marsh,Producer,B,United States,Nevada,EPSG:4326,POINT (-117.63981 37.75272),...,NaN,million tonnes,NaN,percent,Lacustrine brine lithium,Brine,Basin evaporative,0.982076,"algorithm predictions, SRI deposit type classi...",POINT (-117.63981 37.75272)

Export

In [12]:
out_file_csv = PATH_LABELS / "mineral_sites_03_final_filter.csv"
out_file_gpkg = PATH_LABELS / "mineral_sites.gpkg"

mineral_sites_filtered.to_csv(out_file_csv, index=False)
mineral_sites_filtered.to_file(out_file_gpkg, driver="GPKG", layer="mineral_sites_03_final_filter_wkt")

# Create raster

In [13]:
data = mineral_sites_filtered.copy()
data = data.explode(ignore_index=True)
data = data[~data.is_empty]
data = data.reset_index(drop=True)
data = data.to_crs(base_raster.crs)

In [15]:
labels_array = create_binary_raster(data, base_raster, all_touched=False, same_shape=True, fill_negatives=True, out_file=OUT_FILE)
print(f"Number of positive training labels: {np.sum(labels_array==1)}")

Number of positive training labels: 6